<font color='red'>__Import Libraries__</font>

In [75]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
pd.set_option('display.max_rows', 500)

In [41]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

<font color='red'>__Load Dataset__</font>

In [5]:
dataset = pd.read_csv(r'E:\PYTHONCLASSJUPYTER\PrakashSenapati\2024_10_18_Decision Tree\Social_Network_Ads.csv')

In [6]:
dataset.shape

(400, 5)

In [7]:
dataset.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

<font color='red'>__Splitting the dataset into the Training set and Testing set__</font>

In [ ]:
# X = [Age, EstimatedSalary]
# y = [Purchased]

In [30]:
X = dataset.iloc[:, [2, 3]].values
y = dataset.iloc[:, -1].values

In [31]:
print(X.shape)
print(y.shape)

(400, 2)
(400,)


In [32]:
print(X[0:5])

[[   19 19000]
 [   35 20000]
 [   26 43000]
 [   27 57000]
 [   19 76000]]


In [33]:
print(y[0:5])

[0 0 0 0 0]


In [34]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=0)

In [35]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(320, 2)
(80, 2)
(320,)
(80,)


In [36]:
print(X_train[0:5])

[[    58 144000]
 [    59  83000]
 [    24  55000]
 [    26  35000]
 [    58  38000]]


In [37]:
print(y_train[0:5])

[1 0 0 0 1]


In [38]:
print(X_test[0:5])

[[   30 87000]
 [   38 50000]
 [   35 75000]
 [   30 79000]
 [   35 50000]]


In [39]:
print(y_test[0:5])

[0 0 0 0 0]


<font color='red'>__Feature (X_train, X_test) Scaling__</font>

In [42]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [43]:
print(X_train.shape)
print(X_test.shape)

(320, 2)
(80, 2)


In [45]:
print(X_train[0:5])

[[ 1.92295008  2.14601566]
 [ 2.02016082  0.3787193 ]
 [-1.3822153  -0.4324987 ]
 [-1.18779381 -1.01194013]
 [ 1.92295008 -0.92502392]]


In [46]:
print(X_test[0:5])

[[-0.79895082  0.49460758]
 [-0.02126485 -0.57735906]
 [-0.31289709  0.14694273]
 [-0.79895082  0.26283101]
 [-0.31289709 -0.57735906]]


<font color='red'>__Training the Decision Tree Classification model on the Training set__</font>

In [47]:
dt_classifier = DecisionTreeClassifier()
dt_classifier.fit(X_train, y_train)

DecisionTreeClassifier()

<font color='red'>__Predicting the Testing set (X_test)__</font>

In [49]:
y_pred = dt_classifier.predict(X_test)

In [50]:
y_pred.shape

(80,)

In [52]:
print(y_pred)

[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 1 0 1 0 0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 1 1 1 0 0 1 0 0 1 0 1 0 0 0 0 0 1 1 0 0 1
 0 0 0 0 1 1]


In [54]:
print(y_test)

[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 1 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 0 1 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 1 0 0 1
 0 0 0 0 1 1]


In [80]:
actual_predict = pd.concat([pd.DataFrame(y_test, columns=['actual_y']), pd.DataFrame(y_pred, columns=['predicted_y'])], axis=1)

In [81]:
actual_predict['actual_y'].value_counts()

actual_y
0    58
1    22
Name: count, dtype: int64

In [82]:
actual_predict['predicted_y'].value_counts()

predicted_y
0    57
1    23
Name: count, dtype: int64

In [83]:
print(actual_predict)

    actual_y  predicted_y
0          0            0
1          0            0
2          0            0
3          0            0
4          0            0
5          0            0
6          0            0
7          1            1
8          0            0
9          0            0
10         0            0
11         0            0
12         0            0
13         0            0
14         0            0
15         0            1
16         0            1
17         0            0
18         1            1
19         0            0
20         0            0
21         1            1
22         0            0
23         1            1
24         0            0
25         1            0
26         0            0
27         0            0
28         0            0
29         0            0
30         0            0
31         1            0
32         1            1
33         0            0
34         0            0
35         0            0
36         0            0
37         0

<font color='red'>__Making the Confusion Matrix__</font>

In [53]:
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[54  4]
 [ 3 19]]


In [84]:
ac = accuracy_score(y_test, y_pred)
print(ac)

0.9125


In [86]:
bias = dt_classifier.score(X_train, y_train)
bias

0.996875

In [88]:
variance = dt_classifier.score(X_test, y_test)
variance

0.9125